-- Required: primary key on ref_party_link_types.code
-- Columns: code (PK), name, inverse_code, symmetric

-- Symmetric pairs
INSERT INTO ref_party_link_types (code, name, inverse_code, symmetric)
VALUES
  ('spouse',               'is spouse of',               'spouse',               1),
  ('partner',              'is domestic partner of',     'partner',              1),
  ('affiliate_of',         'is affiliate of',            'affiliate_of',         1),
  ('co_borrower_of',       'is co-borrower of',          'co_borrower_of',       1),
  ('same_household_as',    'is in same household as',    'same_household_as',    1),
  ('related_party_of',     'is related party of',        'related_party_of',     1)
ON DUPLICATE KEY UPDATE name=VALUES(name), inverse_code=VALUES(inverse_code), symmetric=VALUES(symmetric);

-- Directed pairs (each side explicit)
INSERT INTO ref_party_link_types (code, name, inverse_code, symmetric) VALUES
  ('parent_of',                'is parent of',                 'child_of',                0),
  ('child_of',                 'is child of',                  'parent_of',               0),
  ('guardian_of',              'is legal guardian of',         'ward_of',                 0),
  ('ward_of',                  'is ward of',                   'guardian_of',             0),
  ('custodian_of',             'is UGMA/UTMA custodian of',    'has_custodian',           0),
  ('has_custodian',            'has UGMA/UTMA custodian',      'custodian_of',            0),
  ('attorney_in_fact_for',     'is attorney-in-fact for',      'has_attorney_in_fact',    0),
  ('has_attorney_in_fact',     'has attorney-in-fact',         'attorney_in_fact_for',    0),
  ('representative_payee_for', 'is representative payee for',  'has_representative_payee',0),
  ('has_representative_payee', 'has representative payee',     'representative_payee_for',0),
  ('employer_of',              'is employer of',               'employee_of',             0),
  ('employee_of',              'is employee of',               'employer_of',             0),
  ('contractor_of',            'is contractor of',             'client_of',               0),
  ('client_of',                'is client of',                 'contractor_of',           0),
  ('advisor_of',               'is financial advisor of',      'advised_by',              0),
  ('advised_by',               'is advised by',                'advisor_of',              0),
  ('accountant_for',           'is accountant for',            'has_accountant',          0),
  ('has_accountant',           'has accountant',               'accountant_for',          0),
  ('attorney_for',             'is legal counsel for',         'has_attorney',            0),
  ('has_attorney',             'has legal counsel',            'attorney_for',            0),
  ('vendor_of',                'is vendor of',                 'customer_of',             0),
  ('customer_of',              'is customer of',               'vendor_of',               0),
  ('owner_of',                 'is legal owner of',            'owned_by',                0),
  ('owned_by',                 'is owned by',                  'owner_of',                0),
  ('beneficial_owner_of',      'is beneficial owner of',       'has_beneficial_owner',    0),
  ('has_beneficial_owner',     'has beneficial owner',         'beneficial_owner_of',     0),
  ('shareholder_of',           'is shareholder of',            'has_shareholder',         0),
  ('has_shareholder',          'has shareholder',              'shareholder_of',          0),
  ('member_of_llc',            'is LLC member of',             'has_member',              0),
  ('has_member',               'has LLC member',               'member_of_llc',           0),
  ('manager_of_llc',           'is LLC manager of',            'has_manager',             0),
  ('has_manager',              'has LLC manager',              'manager_of_llc',          0),
  ('officer_of',               'is officer of',                'has_officer',             0),
  ('has_officer',              'has officer',                  'officer_of',              0),
  ('director_of',              'is director of',               'has_director',            0),
  ('has_director',             'has director',                 'director_of',             0),
  ('control_person_of',        'is control person of',         'has_control_person',      0),
  ('has_control_person',       'has control person',           'control_person_of',       0),
  ('parent_company_of',        'is parent company of',         'subsidiary_of',           0),
  ('subsidiary_of',            'is subsidiary of',             'parent_company_of',       0),
  ('franchisor_of',            'is franchisor of',             'franchisee_of',           0),
  ('franchisee_of',            'is franchisee of',             'franchisor_of',           0),
  ('guarantor_of',             'is guarantor of',              'has_guarantor',           0),
  ('has_guarantor',            'has guarantor',                'guarantor_of',            0),
  ('co_signer_of',             'is co-signer of',              'has_co_signer',           0),
  ('has_co_signer',            'has co-signer',                'co_signer_of',            0),
  ('pledgor_of',               'is collateral pledgor of',     'has_pledgor',             0),
  ('has_pledgor',              'has collateral pledgor',       'pledgor_of',              0),
  ('trustee_of',               'is trustee of',                'has_trustee',             0),
  ('has_trustee',              'has trustee',                  'trustee_of',              0),
  ('settlor_of',               'is settlor of',                'has_settlor',             0),
  ('has_settlor',              'has settlor',                  'settlor_of',              0),
  ('protector_of',             'is protector of',              'has_protector',           0),
  ('has_protector',            'has protector',                'protector_of',            0),
  ('beneficiary_of',           'is beneficiary of',            'has_beneficiary',         0),
  ('has_beneficiary',          'has beneficiary',              'beneficiary_of',          0),
  ('executor_of',              'is executor of',               'has_executor',            0),
  ('has_executor',             'has executor',                 'executor_of',             0),
  ('personal_representative_of','is personal representative of','has_personal_representative',0),
  ('has_personal_representative','has personal representative','personal_representative_of',0),
  ('agent_of',                 'is agent of',                  'principal_of',            0),
  ('principal_of',             'is principal of',              'agent_of',                0),
  ('reference_for',            'is reference for',             'referred_by',             0),
  ('referred_by',              'is referred by',               'reference_for',           0),
  ('introduced',               'introduced',                   'introduced_by',           0),
  ('introduced_by',            'introduced by',                'introduced',              0)
ON DUPLICATE KEY UPDATE name=VALUES(name), inverse_code=VALUES(inverse_code), symmetric=VALUES(symmetric);
