default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bankencore
  password: Katikoan123
  host: localhost

development:
  <<: *default
  database: betest2_development

test:
  <<: *default
  database: bestest2_test

production:
  <<: *default
  database: betest2_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>